Serialization
biocircuits/bioscrape pull request #97
Opened 2021-04-03 21:13 UTC by sclamons

This branch:
1) Adds the ability to pickle and unpickle Term, Model, and LineageModel objects. This allows Models/LineageModels to work with copy.copy/deepcopy and be passed directly with multiprocessing.
2) Adds tests for pickling and unpickling Models and LineageModels.
3) Refactors some Term subclasses into subclasses of BinaryTerm(Term), which swallows some redundant code. 
4) Refactors the tests in test_propensities_via_annotations.py into a single parameterized test.

2021-04-03 21:24 UTC, WilliamIX requested changes
Looks pretty good! two minor requests then I think we can merge.

2021-04-03 21:24 UTC, WilliamIX commented on tests/test_serialization.py
> +	delay_k = round(np.exp(np.random.uniform(low = -1,
Delays are actually not currently supported in lineages due to complications partitioning the delay queue objects, so don't need to include this in the tests.

2021-04-03 21:24 UTC, WilliamIX commented on tests/test_serialization.py
> +	prepickling_results = py_simulate_model(timepoints,
Can we ensure this works with deterministic simulations as well?

2021-04-03 21:26 UTC, sclamons commented
These make sense to me.


On Sat, Apr 3, 2021 at 2:24 PM William Poole ***@***.***>
wrote:

> *@WilliamIX* requested changes on this pull request.
>
> Looks pretty good! two minor requests then I think we can merge.
> ------------------------------
>
> In tests/test_serialization.py
> <https://github.com/biocircuits/bioscrape/pull/97#discussion_r606712164>:
>
> > +		exp = str(round(np.random.uniform(low = 0,high = param_max), 3))
> +		species = all_species[np.random.randint(len(all_species))]
> +		rate_str += coef + "*" + species + "^" + exp + "+"
> +	rate_str =  rate_str[:-1] + ")"
> +	param_dict['rate'] = rate_str
> +	if debug:
> +		print('\t params =', param_dict)
> +
> +
> +	### DELETEME
> +	param_dict["rate"] = "A*3"
> +
> +	consolidation_rxn = (inputs, outputs, "general", param_dict)
> +
> +	# We'll add an A-->B reaction with delay.
> +	delay_k = round(np.exp(np.random.uniform(low = -1,
>
> Delays are actually not currently supported in lineages due to
> complications partitioning the delay queue objects, so don't need to
> include this in the tests.
> ------------------------------
>
> In tests/test_serialization.py
> <https://github.com/biocircuits/bioscrape/pull/97#discussion_r606712238>:
>
> > +			  initial_condition_dict = x0)
> +	M.set_species(x0)
> +
> +
> +    # Finally, to test assignment rules, we'll add a rule adding an "inducer" at
> +    # time 75.
> +	M.create_parameter("I0", 10) #Inducer concentration
> +	M.create_parameter("T_I0", 2) #Initial time inducer is added
> +	M.create_rule("assignment", {"equation":"I = _I0*Heaviside(t-_T_I0)"})
> +
> +
> +	###############################
> +	# TEST SERIALIZATION OF MODEL #
> +	###############################
> +	timepoints = np.arange(0, 25, 0.01)
> +	prepickling_results = py_simulate_model(timepoints,
>
> Can we ensure this works with deterministic simulations as well?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/biocircuits/bioscrape/pull/97#pullrequestreview-627487306>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAM7DU33SS2HOVXIUCW7CTTTG6BSLANCNFSM42KUI4OQ>
> .
>

2021-05-01 01:49 UTC, sclamons commented
Added deterministic simulation checks alongside the stochastic simulation checks. They're producing some results with NaNs (not entirely NaNs, but some NaNs), but they're _reproducibly_ returning the same results before and after pickling. 

I'm leaving the checks on LineageModels with delay reactions, so that if we ever get around to adding delays these tests will be ready. These tests will still run just fine on LineageModels with delay reactions as long as lineages's behavior is to ignore the delays -- we can't check Model equality directly anyway (that would require a patch's worth of added code), so we can only readily check "equality" by looking at simulation results.

2021-06-05 04:12 UTC, WilliamIX approved these changes

2021-06-07 02:53 UTC, merged