Turbidostat
biocircuits/bioscrape pull request #98
Opened 2021-04-30 23:27 UTC by sclamons

Adds turbidostat functionality to bioscrape.lineages, along with unit tests of a priority queue implemented for turbidostat simulations. Does _not_ add integration tests of any of the SimulateTurbidostat functions.

2021-05-26 18:22 UTC, WilliamIX requested changes

2021-06-01 20:47 UTC, sclamons commented on setup.py
> +    if install_pqtest:
Cruft left over from some internal testing. I'll delete these bits.

2021-06-01 20:53 UTC, sclamons commented on bioscrape/types.pyx
> +        param_names = [s for s in names if (s not in species2index and s != 'volume' and s != 't')]
How about we issue a PendingDeprecationWarning if either one isn't there, and then we can actually deprecate it later. That will keep us from accidentally releasing something broken by the change AND warn us of what we need to update.

2021-06-01 20:57 UTC, WilliamIX commented on bioscrape/types.pyx
> +        param_names = [s for s in names if (s not in species2index and s != 'volume' and s != 't')]
We have been including this warning elsewhere for months now - the "_" won't actually hurt anything I believe. However, I don't want the code to not work with new models that don't use this convention.

2021-06-01 21:28 UTC, WilliamIX approved these changes

2021-06-07 02:53 UTC, merged